#!/bin/bash

sudo service pyserver stop

echo *pyserver stopped*

sudo rm /etc/systemd/system/pyserver.service

echo *pyserver removed from /etc*

sudo userdel -r pythonadm

echo *user profiles deleted*
